### ISSUE TITLE
E1M1 has a part of the map you can escape

### ISSUE THREAD

**Issue by blitzdoughnuts** [SmekkyBoy/Biff-Fraggar#3]
In E1M1, where all the parts you're not intended to go through are sealed shut, there;'s one loose area without the Impassable linedef flag.

Valve, please fix.

**Comment by SmekkyBoy** [comment]
Fixed (Thanks to you), gonna push a new commit soon

**Comment by rostuhan** [comment]
Why isn't this issue closed yet?

**Comment by rostuhan** [comment]
Oh, there was no commit yet.
